### ISSUE TITLE
postgis port change

### ISSUE THREAD

**Issue by jmarpi** [3liz/lizmap-docker-compose#21]
Hi, I have the following issue:
On my ubuntu 20.0.4 OS, a postgres container is running on port 5432 with another service.
Modify the file: env.default
The value of `POSTGIS_PORT= ${POSTGIS_PORT:-"127.0.0.1:5433"}`
ie change the port from 5432 to 5433

execute 
`make  configure`
and then
`docker-compose up`

and I have the following error:

ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported configuration option for services.postgis: 'profiles'

any idea how to solve?

**Comment by dmarteau** [comment]
You have two unrelated questions: one about the port change, the other about the docker-compose problem.

About the docker-compose `profiles` configuration: your docker-compose is too old, please update your docker-compose, your docker-compose must support the versions 3.9 of the docker-compose file.

See https://docs.docker.com/compose/profiles/

Otherwise remove the `profile` from the docker-compose file.

Hint: use the python version of docker-compose in a venv.

Abount the port: expose the port you want, the `.env` file is generated by the Makefile (see README) and not under revision control.

**Comment by jmarpi** [comment]
@dmarteau Thank you very much for your help, it actually worked by removing the postgis service.
