### ISSUE TITLE
Error 500. A technical error has occured. Sorry for this trouble.

### ISSUE THREAD

**Issue by tuankhanh78** [3liz/lizmap-docker-compose#43]
Hi,

I have an error when I clic on Administration.
This happen when I restart my container .

I get the following message in the errors.log

2022-12-23 15:41:05     37.65.2.147     error   2022-12-23 15:41:05     [18]    Module inconnu dans le sélecteur "jauth~login:out@classic"      /www/lib/jelix/core/selector/jSelectorAct.class.php 70

Thank for your help
Regards

**Comment by Gustry** [comment]
Can you specify versions you used ? Such as following this link https://docs.lizmap.com/current/en/publish/lizmap_plugin/information.html#request-for-support

**Comment by tuankhanh78** [comment]
Hi 

I use the last lizmap-docker-compose.
Lizmap version 3.5
QGIS version : 3.22.13

Thank

**Comment by cybernar** [comment]
Hello, 
I have a similar error on Linux Ubuntu 22.04.

- The first time I launch `docker compose up -d` : everything's OK, I can access the admin console, change the password and add a repository. 
- The second time, after `docker compose down` and `docker compose up -d` : the project is still visible, but I can't access the admin console anymore. First, the login screen is not normal looking, it looks like the css are broken. Second, I get : "Error 500. A technical error has occured. Sorry for this trouble"

My config :  

**Versions :**

* Lizmap Web Client : 3.5.10
* Lizmap Web Client target version : 3.5
* Lizmap plugin : 3.10.1
* QGIS Desktop : 3.22.16
* QGIS Server : 3.22.15
* Py-QGIS-Server : 1.8.7
* QGIS Server plugin atlasprint : 3.3.2
* QGIS Server plugin lizmap_server : 1.3.1
* QGIS Server plugin wfsOutputExtension : 1.7.1

Note : I have configured Lizmap .env with LIZMAP_UID=1000 and LIZMAP_GID=1000 (my account) 

Cyril

**Comment by cybernar** [comment]
Update : I tried Lizmap Web Client 3.6.1 instead of 3.5.10, after cleaning configuration and removing named volumes. 

Now it works ! I can stop and restart the stack, and access the admin console.

My new config : 

**Versions :**

* Lizmap Web Client : 3.6.1
* Lizmap Web Client target version : 3.6
* Lizmap plugin : 3.10.1
* QGIS Desktop : 3.22.16
* QGIS Server : 3.22.15
* Py-QGIS-Server : 1.8.7
* QGIS Server plugin atlasprint : 3.3.2
* QGIS Server plugin lizmap_server : 1.3.1
* QGIS Server plugin wfsOutputExtension : 1.7.1

There seems to be a problem with 3.5.10. I've tried to clean & reinstall it many times, always with the same problem (

**Comment by Gustry** [comment]
Thanks for the update !

Is the admin panel working well with your 3.6.1 ? (all panels are visible ?)

Do not forget to make a `docker compose pull` from time to time, it will download QGIS Server : 3.22.16, you are on .15. It will be more important in a few months for instance.

**Comment by cybernar** [comment]
I think everything is OK with the admin panel in 3.6.1 
(but I have not tried all the new features yet !)
